### PR TITLE
Point to 5.4.1 StackiOS iso image

### PR DESCRIPTION
**Pull request by snkgak**
Point to working StackiOS 5.4.1 ISO image while 5.6 is wrapping up and 5.6 Documentation is completed.

### CODE REVIEW

**Comment by bsanders** [comment]
@snkgak thanks for looking at this!  Would you mind pointing the docs at the 5.4.1 non-stackios release too?

https://github.com/Teradata/stacki/releases/download/stacki-5.4.1/stacki-5.4.1-redhat7.x86_64.disk1.iso

md5's:
```
9e1c159ec4a34396b0d4c9c88d6c0b95  stacki-5.4.1-redhat7.x86_64.disk1.iso
03daf2291e8d6617f8ae1f4d5e821ed6  stackios-5.4.1-redhat7.x86_64.disk1.iso
```

**Comment by snkgak** [comment]
Done.

**Comment by snkgak** [comment]
@caladd Can we make this public? - wiki is still pointing folks to a broke image.

**Comment by bsanders** [comment]
Got you.  Thanks for the poke.

**Pull request merged**
